// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxnAB2tp5hjVIT8v-V7sqpZas4S_zEPHY',
    appId: '1:660264530251:web:6253341974346665bb78ce',
    messagingSenderId: '660264530251',
    projectId: 'senior-pass-step',
    authDomain: 'senior-pass-step.firebaseapp.com',
    storageBucket: 'senior-pass-step.firebasestorage.app',
    measurementId: 'G-GYGRH23MMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbabRN3XFNQGlNvssL7g5brxxqtB-jgYU',
    appId: '1:660264530251:android:558c4a6c9d390e69bb78ce',
    messagingSenderId: '660264530251',
    projectId: 'senior-pass-step',
    storageBucket: 'senior-pass-step.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCazThpDXXQL_ED3cWgvkiyoxWXi1wbglA',
    appId: '1:660264530251:ios:0a3058767c37849cbb78ce',
    messagingSenderId: '660264530251',
    projectId: 'senior-pass-step',
    storageBucket: 'senior-pass-step.firebasestorage.app',
    iosBundleId: 'com.example.seniorsteppassSource',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCazThpDXXQL_ED3cWgvkiyoxWXi1wbglA',
    appId: '1:660264530251:ios:0a3058767c37849cbb78ce',
    messagingSenderId: '660264530251',
    projectId: 'senior-pass-step',
    storageBucket: 'senior-pass-step.firebasestorage.app',
    iosBundleId: 'com.example.seniorsteppassSource',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxnAB2tp5hjVIT8v-V7sqpZas4S_zEPHY',
    appId: '1:660264530251:web:3edb99fd367bb16cbb78ce',
    messagingSenderId: '660264530251',
    projectId: 'senior-pass-step',
    authDomain: 'senior-pass-step.firebaseapp.com',
    storageBucket: 'senior-pass-step.firebasestorage.app',
    measurementId: 'G-TKPC5RJXNN',
  );
}
